/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import com.sun.webkit.dom.EventImpl;

import AppPackage.AnimationClass;
import javax.swing.JOptionPane;
        

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpentrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlbInternet = new javax.swing.JLabel();
        jlbCuladora = new javax.swing.JLabel();
        jlbMusica = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpmenu1 = new javax.swing.JLabel();
        jpDrive = new javax.swing.JLabel();
        jpmenu3 = new javax.swing.JLabel();
        jpmenu4 = new javax.swing.JLabel();
        jpmenu5 = new javax.swing.JLabel();
        jpmenu6 = new javax.swing.JLabel();
        jLDriver = new javax.swing.JLabel();
        jLCronograma = new javax.swing.JLabel();
        jLAnotações = new javax.swing.JLabel();
        jLEventos = new javax.swing.JLabel();
        jLSocios = new javax.swing.JLabel();
        jLAjustes = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlbMinimizar = new javax.swing.JLabel();
        jlbFechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpentrar.setBackground(new java.awt.Color(255, 255, 255));
        jpentrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpentrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Password:");
        jpentrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("User:");
        jpentrar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jpentrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 70));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Usuario");
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jpentrar.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, 30));
        jpentrar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 220, 20));
        jpentrar.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("password");
        jPasswordField1.setBorder(null);
        jpentrar.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jpentrar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));
        jpentrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user24.png"))); // NOI18N
        jpentrar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));
        jpentrar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/key24.png"))); // NOI18N
        jpentrar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enter.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enterON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enterON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/enterON.png"))); // NOI18N
        jpentrar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 60, 30));

        jlbInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_32px.png"))); // NOI18N
        jlbInternet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpentrar.add(jlbInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, -1, -1));

        jlbCuladora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        jlbCuladora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpentrar.add(jlbCuladora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 90, -1, -1));

        jlbMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Musical_Notes_32px.png"))); // NOI18N
        jlbMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpentrar.add(jlbMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 130, -1, -1));

        getContentPane().add(jpentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpmenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/analyze (1).png"))); // NOI18N
        jpmenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jpmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 180, 160));

        jpDrive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpDrive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/google-drive.png"))); // NOI18N
        jpDrive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpDrive.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpDriveMouseMoved(evt);
            }
        });
        jpDrive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpDriveMouseExited(evt);
            }
        });
        jPanel1.add(jpDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 180, 160));

        jpmenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clock-circular-outline.png"))); // NOI18N
        jpmenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jpmenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 180, 160));

        jpmenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/creative.png"))); // NOI18N
        jpmenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jpmenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 180, 160));

        jpmenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendar-with-a-clock-time-tools.png"))); // NOI18N
        jpmenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jpmenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 160));

        jpmenu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpmenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hand-shake.png"))); // NOI18N
        jpmenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jpmenu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, 160));

        jLDriver.setBackground(new java.awt.Color(181, 11, 33));
        jLDriver.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLDriver.setForeground(new java.awt.Color(181, 11, 33));
        jLDriver.setText("Drive");
        jPanel1.add(jLDriver, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLCronograma.setBackground(new java.awt.Color(181, 11, 33));
        jLCronograma.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLCronograma.setForeground(new java.awt.Color(181, 11, 33));
        jLCronograma.setText("Cronograma");
        jPanel1.add(jLCronograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLAnotações.setBackground(new java.awt.Color(181, 11, 33));
        jLAnotações.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLAnotações.setForeground(new java.awt.Color(181, 11, 33));
        jLAnotações.setText("Anatações");
        jPanel1.add(jLAnotações, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLEventos.setBackground(new java.awt.Color(181, 11, 33));
        jLEventos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLEventos.setForeground(new java.awt.Color(181, 11, 33));
        jLEventos.setText("Eventos");
        jPanel1.add(jLEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jLSocios.setBackground(new java.awt.Color(181, 11, 33));
        jLSocios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLSocios.setForeground(new java.awt.Color(181, 11, 33));
        jLSocios.setText("Socios");
        jPanel1.add(jLSocios, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        jLAjustes.setBackground(new java.awt.Color(181, 11, 33));
        jLAjustes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLAjustes.setForeground(new java.awt.Color(181, 11, 33));
        jLAjustes.setText("Ajustes");
        jPanel1.add(jLAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/magnifier.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Buscar...");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 220, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jlbMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMinimizarMouseClicked(evt);
            }
        });
        jPanel2.add(jlbMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, 30));

        jlbFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jlbFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbFecharMouseClicked(evt);
            }
        });
        jPanel2.add(jlbFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     
        
        //--->
        
        AnimationClass internet = new AnimationClass();
        internet.jLabelXRight(-40, 10, 10, 5, jlbInternet);
        
         AnimationClass calculadora = new AnimationClass();
        calculadora.jLabelXRight(-40,10, 10, 5, jlbCuladora);
        
         AnimationClass musica  = new AnimationClass();
        musica.jLabelXRight(-40,10, 10, 5, jlbMusica);
        
        
        //<---
        
        AnimationClass internett = new AnimationClass();
        internett.jLabelXLeft(10, -40, 10, 5, jlbInternet);
        
         AnimationClass calculadoraa = new AnimationClass();
        calculadoraa.jLabelXLeft(10, -40, 10, 5, jlbCuladora);
        
         AnimationClass musicaa  = new AnimationClass();
        musicaa.jLabelXLeft(10, -40, 10, 5, jlbMusica);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jlbFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbFecharMouseClicked
        // TODO add your handling code here:
        
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Deseja sair do Login?", "Exit", dialog);
        if(result == 0)
                {
                    System.exit(0);
                }
        
    }//GEN-LAST:event_jlbFecharMouseClicked

    private void jlbMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMinimizarMouseClicked
        // TODO add your handling code here:
        
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jlbMinimizarMouseClicked

    private void jpDriveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDriveMouseMoved
        // TODO add your handling code here:
        jpDrive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jpDriveMouseMoved

    private void jpDriveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpDriveMouseExited
        // TODO add your handling code here:
        jpDrive.setBorder(null);
    }//GEN-LAST:event_jpDriveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAjustes;
    private javax.swing.JLabel jLAnotações;
    private javax.swing.JLabel jLCronograma;
    private javax.swing.JLabel jLDriver;
    private javax.swing.JLabel jLEventos;
    private javax.swing.JLabel jLSocios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlbCuladora;
    private javax.swing.JLabel jlbFechar;
    private javax.swing.JLabel jlbInternet;
    private javax.swing.JLabel jlbMinimizar;
    private javax.swing.JLabel jlbMusica;
    private javax.swing.JLabel jpDrive;
    private javax.swing.JPanel jpentrar;
    private javax.swing.JLabel jpmenu1;
    private javax.swing.JLabel jpmenu3;
    private javax.swing.JLabel jpmenu4;
    private javax.swing.JLabel jpmenu5;
    private javax.swing.JLabel jpmenu6;
    // End of variables declaration//GEN-END:variables
}
